// TOPSPIN — bibliothèque d'entraînement tennis de table (niveau confirmé/compétition)
// Drill : {id, name, cat, dur (min conseillées), desc, but, variantes[], critere}
const CATS = [
 {id:"echauf", name:"Échauffement", icon:"🔥", gen:"warm"},
 {id:"gammes", name:"Gammes & régularité", icon:"🎯", gen:"warm2"},
 {id:"services", name:"Services", icon:"🎱", gen:"theme"},
 {id:"remise", name:"Remise de service", icon:"🛡️", gen:"theme"},
 {id:"cd", name:"Topspin coup droit", icon:"💥", gen:"theme"},
 {id:"rv", name:"Revers", icon:"🌀", gen:"theme"},
 {id:"jambes", name:"Jeu de jambes", icon:"👟", gen:"theme"},
 {id:"bloc", name:"Bloc & contre", icon:"🧱", gen:"theme"},
 {id:"schemas", name:"Schémas de jeu", icon:"♟️", gen:"situ"},
 {id:"match", name:"Situations de match", icon:"🏆", gen:"situ"},
 {id:"physique", name:"Physique spécifique", icon:"🏋️", gen:"theme"},
 {id:"retour", name:"Retour au calme", icon:"🧘", gen:"cool"}
];

const DRILLS = [
// ÉCHAUFFEMENT
{id:"e1", name:"Corde à sauter", cat:"echauf", dur:5,
desc:"3 à 5 minutes de corde : pieds joints, puis alterné, puis double-unders si à l'aise. Monte progressivement le rythme cardiaque et réveille les mollets — la première qualité d'un pongiste, ce sont les appuis.",
but:"Température corporelle + réactivité des chevilles avant de toucher une raquette.",
variantes:["30s rapide / 30s lent × 5","Sur un pied, 20 sauts chacun"],
critere:"Légère sudation, chevilles réactives, zéro raideur."},
{id:"e2", name:"Mobilité dynamique complète", cat:"echauf", dur:6,
desc:"Circuit : rotations d'épaules bâton ou élastique, rotations de hanches, fentes marchées avec rotation du buste, moulinets de poignet, cercles de cheville. Tout en mouvement, jamais statique avant l'effort.",
but:"Préparer épaule, hanche et poignet — les trois articulations qui encaissent le topspin.",
variantes:["Ajouter des squats sautés légers en fin de circuit"],
critere:"Amplitude complète sans douleur sur chaque articulation."},
{id:"e3", name:"Gammes CD-CD diagonale", cat:"echauf", dur:5,
desc:"Coup droit sur coup droit en diagonale, cadence moyenne, concentration sur le relâchement et le placement du corps derrière chaque balle. Ce n'est PAS un échange automatique : chaque balle a une intention de placement.",
but:"Régler la main, le timing et la distance à la table.",
variantes:["Monter la cadence par paliers de 30 s","Varier la longueur : mi-table puis fond de table"],
critere:"50 balles sans faute à cadence moyenne, corps placé (pas que le bras)."},
{id:"e4", name:"Gammes RV-RV diagonale", cat:"echauf", dur:5,
desc:"Même logique côté revers : diagonale revers, coude stable, contact devant le corps. Chercher le petit accompagnement du poignet sur chaque balle, pas un bloc passif.",
but:"Activer le revers comme un coup d'attaque, pas de survie.",
variantes:["Alterner 5 blocs / 5 tops légers","Décaler progressivement vers le milieu"],
critere:"50 balles sans faute, contact devant le corps, poignet actif."},
// GAMMES
{id:"g1", name:"8 CD / 8 RV alternés", cat:"gammes", dur:8,
desc:"Huit coups droits diagonale puis huit revers diagonale, sans interruption, le partenaire bloque. La transition entre les deux séquences se fait en jouant, pas en s'arrêtant. Réduire ensuite à 4/4 puis 2/2.",
but:"Automatiser la transition CD/RV avec replacement systématique.",
variantes:["4/4 puis 2/2 puis 1/1 (le plus dur)","Le bloqueur varie légèrement la longueur"],
critere:"3 cycles complets 2/2 sans faute ni retard de replacement."},
{id:"g2", name:"Milieu-CD, milieu-RV", cat:"gammes", dur:8,
desc:"Le partenaire envoie une balle au milieu (ventre) puis une balle dans un coin, en alternance. Tu choisis CD ou RV sur la balle du milieu — décision + jeu de jambes à chaque balle. Le milieu est la zone qui fait perdre les matchs.",
but:"Tuer l'indécision sur la balle au corps.",
variantes:["Coin imposé puis coin libre","Le relanceur annonce « pivot ! » aléatoirement"],
critere:"20 balles au corps traitées sans balle subie (pas de coup « coincé »)."},
{id:"g3", name:"Cadence progressive 3 paliers", cat:"gammes", dur:6,
desc:"Échange régulier CD-CD : 1 minute cadence confort, 1 minute cadence match, 1 minute cadence au-dessus du confort (où la technique commence à se dégrader). C'est le dernier palier qui fait progresser — reste relâché malgré la vitesse.",
but:"Repousser la vitesse maximale à technique constante.",
variantes:["Même chose en RV-RV","Palier 3 en contre-top mi-distance"],
critere:"Au palier 3 : plus de 15 balles d'affilée en gardant le geste complet."},
{id:"g4", name:"Régularité mi-distance", cat:"gammes", dur:7,
desc:"Recule d'un mètre à un mètre cinquante : échange topspin sur topspin ou top sur bloc long, en cherchant la constance de trajectoire et la rotation. Le jeu à mi-distance est ce qui sépare le joueur de club du compétiteur.",
but:"Construire la sécurité de rotation quand on est éjecté de la table.",
variantes:["Un joueur à la table (bloc), l'autre à mi-distance","Les deux à mi-distance en contre-top coopératif"],
critere:"20 topspins consécutifs depuis la mi-distance sans raccourcir le geste."},
// SERVICES
{id:"s1", name:"Service court coupé — cible serviette", cat:"services", dur:10,
desc:"Pose une serviette pliée (ou une feuille A5) sur la zone visée côté adverse, près du filet. Série de services pendule courts coupés : la balle doit rebondir DEUX fois sur la demi-table adverse si on la laisse. Compte tes touches de cible sur 20.",
but:"Un court coupé métronomique — la base de toute construction du point au niveau compétition.",
variantes:["Varier coupé pur / coupé-latéral avec le même geste","Alterner cible coin CD / milieu / coin RV"],
critere:"12/20 sur la cible avec double rebond. En dessous de 8, tu refais la série."},
{id:"s2", name:"Service long rapide surprise", cat:"services", dur:6,
desc:"Travaille le service long rapide dans le coin revers (ou au coude) avec le MÊME début de geste que ton court coupé. Toute la valeur du long est dans la dissimulation : s'il est lisible, c'est un cadeau.",
but:"Rendre long et court indistinguables jusqu'au contact.",
variantes:["Filme 10 services mélangés : le début de geste doit être identique","Long latéral sortant côté CD pour varier"],
critere:"La balle touche le fond de table adverse à moins de 30 cm de la ligne, 7/10."},
{id:"s3", name:"Effets : pendule inversé & tomahawk", cat:"services", dur:10,
desc:"Séance dédiée aux services « seconde gamme » : pendule inversé (reverse) et tomahawk. Objectif : en maîtriser au moins un assez bien pour le sortir 3-4 fois par match et casser le rythme de lecture adverse.",
but:"Ajouter une vraie variation d'effet latéral opposé à ton service principal.",
variantes:["Reverse court / reverse long dans le coude","Tomahawk long côté CD adverse"],
critere:"7/10 services reverse dans la zone visée avec l'effet clairement présent."},
{id:"s4", name:"20 services d'intention", cat:"services", dur:8,
desc:"20 services enchaînés, mais AVANT chaque service tu annonces à voix haute : effet, longueur, placement, et la 3ᵉ balle attendue. Le service n'est pas un coup isolé, c'est la première pièce d'un schéma.",
but:"Connecter chaque service à un plan de point.",
variantes:["Un partenaire remet et tu joues réellement la 3ᵉ balle annoncée"],
critere:"16/20 services conformes à l'annonce (effet ET zone)."},
{id:"s5", name:"Services filmés — l'audit", cat:"services", dur:8,
desc:"Téléphone posé côté relanceur, filme 15 services variés. Regarde ensuite au ralenti : le contact est-il visible ? Le geste trahit-il la longueur ? C'est l'exercice le plus rentable et le moins pratiqué.",
but:"Voir tes services comme l'adversaire les voit.",
variantes:["Fais deviner l'effet à un partenaire qui ne regarde que la vidéo"],
critere:"Identifier UN défaut de dissimulation précis et le corriger sur 10 services."},
// REMISE
{id:"r1", name:"Remise courte sur court (toucher)", cat:"remise", dur:8,
desc:"Le partenaire sert court coupé, tu remets court — double rebond exigé. Main relâchée, raquette qui « accueille » la balle sous la table de la main libre presque. Le remise courte tue la 3ᵉ balle adverse.",
but:"Neutraliser le serveur en refusant l'ouverture.",
variantes:["Remise courte croisée / décroisée sur annonce tardive","Alterner courte / poussette longue rapide 2-1"],
critere:"7/10 remises avec double rebond sans balle haute."},
{id:"r2", name:"Flip banane sur service court", cat:"remise", dur:10,
desc:"Sur service court (même coupé), attaque de revers par-dessus la table avec frottement latéral — la banane. Monte sur la pointe des pieds, coude haut, contact sur le côté de la balle. L'arme n°1 du jeu moderne sur balle courte.",
but:"Transformer la remise en première attaque.",
variantes:["Banane croisée puis ligne droite","Banane sur coupé fort (plus de frottement, moins de vitesse)"],
critere:"6/10 bananes qui mettent le serveur en défense (bloc ou balle subie)."},
{id:"r3", name:"Poussette longue placée", cat:"remise", dur:6,
desc:"Poussette rapide, longue, très coupée, placée dans les coins ou au coude — pas une poussette de confort au milieu. Une bonne poussette longue est une attaque déguisée qui force un top de mauvaise qualité.",
but:"Faire de la poussette un coup offensif à part entière.",
variantes:["Poussette longue puis bloc actif sur le top adverse (enchaînement)"],
critere:"8/10 poussettes qui atterrissent à moins de 40 cm du fond, coins ou coude."},
{id:"r4", name:"Remise du service long : top d'entrée", cat:"remise", dur:8,
desc:"Le partenaire sert long (varié : coupé, latéral, rapide), tu prends TOUT en topspin d'entrée, même inconfortable. Interdiction de pousser. Au niveau compétition, un service long doit systématiquement être puni.",
but:"Automatiser la punition du service long.",
variantes:["Top d'entrée croisé sécurité / ligne surprise","Sur service rapide au coude : top revers compact"],
critere:"7/10 services longs attaqués avec une vraie qualité de rotation."},
// TOPSPIN CD
{id:"c1", name:"Top CD sur bloc — montée en cadence", cat:"cd", dur:8,
desc:"Topspin coup droit diagonale sur bloc régulier. Trois paliers de cadence comme en gammes, mais l'accent est sur la reproduction du geste complet à haute vitesse : jambes fléchies, rotation de hanche, relâchement.",
but:"Un top CD qui reste technique sous fatigue et vitesse.",
variantes:["Le bloqueur joue 1 balle sur 4 au milieu","Finir par 10 tops à intensité match"],
critere:"15 tops consécutifs au palier haut sans dégradation visible du geste."},
{id:"c2", name:"Ouverture CD sur poussette", cat:"cd", dur:10,
desc:"Le partenaire pousse long et coupé, tu ouvres en topspin — frottement d'abord, la vitesse vient après. Balle après balle, cherche la trajectoire tendue-mais-sûre au-dessus du filet. L'ouverture sur coupé est LE coup qui gagne les matchs de compétition.",
but:"Une ouverture fiable à 90 % sur n'importe quelle poussette.",
variantes:["Poussettes placées aléatoirement (CD, milieu, RV avec pivot)","Ouverture puis enchaînement sur bloc"],
critere:"9/10 ouvertures dans la table dont 6 qui mettent l'adversaire en difficulté."},
{id:"c3", name:"2 tops CD placés", cat:"cd", dur:8,
desc:"Sur bloc : premier top croisé, deuxième top ligne droite (ou l'inverse), puis le point continue librement. Le changement de direction sur le DEUXIÈME top est ce qui déborde un bon bloqueur.",
but:"Varier la direction sans télégraphier.",
variantes:["Direction du 2ᵉ top annoncée par le bloqueur au dernier moment","3 tops : croisé-croisé-ligne"],
critere:"7/10 séquences où le changement de ligne est propre (pas de balle molle)."},
{id:"c4", name:"Multiball : top sur coupé en déplacement", cat:"cd", dur:10,
desc:"Au panier : le distributeur envoie des balles coupées alternées demi-table CD (une courte-mi-table, une longue), tu ouvres en top CD en te déplaçant. Volume et jambes — le multiball est le simulateur de haute intensité.",
but:"Répéter l'ouverture CD en situation de déplacement réel.",
variantes:["Zones aléatoires sur toute la demi-table","2 coupées + 1 bloc rapide (changement de rythme)"],
critere:"3 séries de 20 balles avec ≥ 16 tops corrects par série."},
// REVERS
{id:"v1", name:"Top revers sur bloc", cat:"rv", dur:8,
desc:"Topspin revers diagonale sur bloc, contact devant le corps, accélération de l'avant-bras et du poignet. Cherche une vraie rotation, pas un « punch » plat — le top revers moderne se joue compact mais frotté.",
but:"Un top revers qui existe comme arme, pas comme dépannage.",
variantes:["Alterner top / bloc actif une balle sur deux","Monter la cadence 3 paliers"],
critere:"15 tops revers consécutifs avec rotation audible/visible."},
{id:"v2", name:"Banane + enchaînement revers", cat:"rv", dur:8,
desc:"Service court adverse → banane → le point continue en diagonale revers (top ou contre). La banane n'a de valeur que si tu es prêt pour la balle SUIVANTE : replace-toi immédiatement après le flip.",
but:"Connecter la banane au reste du point.",
variantes:["Banane ligne droite puis pivot CD sur le retour","Banane puis jeu libre en 11 points"],
critere:"6/10 séquences banane + 2ᵉ coup gagnés ou dominés."},
{id:"v3", name:"Transition revers → pivot CD", cat:"rv", dur:8,
desc:"Deux tops revers dans la diagonale, puis le partenaire bloque au milieu-revers : pivot et coup droit. La décision de pivoter doit se prendre PENDANT le coup précédent, pas après le rebond.",
but:"Un pivot déclenché tôt, sans balle « entre deux ».",
variantes:["Pivot puis grand écart CD sur bloc croisé (Falkenberg partiel)","Nombre de revers avant pivot aléatoire (1 à 3)"],
critere:"8/10 pivots pris à temps (contact devant, pas en retard sur le côté)."},
// JEU DE JAMBES
{id:"j1", name:"Falkenberg", cat:"jambes", dur:10,
desc:"LE classique suédois : revers, pivot coup droit (même coin), grand écart coup droit (coin opposé), et on recommence. Trois balles, trois déplacements différents. Cadence continue, le bloqueur est régulier.",
but:"Les trois déplacements fondamentaux enchaînés sous cadence.",
variantes:["Version miroir (départ CD)","Le bloqueur accélère progressivement"],
critere:"5 cycles complets sans faute, puis 8, puis 10 — note ton record."},
{id:"j2", name:"2 CD 1 RV en déplacement", cat:"jambes", dur:8,
desc:"Deux coups droits (coin CD puis milieu) puis un revers, en continu. Force le petit déplacement latéral répété côté coup droit — celui qu'on néglige — puis la transition revers.",
but:"Vitesse des petits pas d'ajustement.",
variantes:["Inverser : 2 RV 1 CD","Le bloqueur choisit milieu ou coin sur la 2ᵉ balle"],
critere:"10 cycles sans balle prise en retard."},
{id:"j3", name:"Shadow — étoile aux coins", cat:"jambes", dur:5,
desc:"Sans balle : touche les deux coins de la table et le milieu en enchaînant les déplacements chassés avec geste complet (top CD au coin CD, pivot au coin RV...). 30 secondes d'effort / 30 de repos.",
but:"Volume de jambes pur, sans contrainte de balle.",
variantes:["Avec élastique de résistance à la taille","Raquette lestée légère"],
critere:"6 rounds de 30/30 en gardant la fréquence d'appuis du 1er round."},
{id:"j4", name:"Multiball aléatoire 2 → 3 zones", cat:"jambes", dur:10,
desc:"Au panier : distribution aléatoire sur 2 zones (coin CD / coin RV), tout en topspin. Quand le taux de réussite dépasse 80 %, passe à 3 zones (+ milieu). L'aléatoire est le seul vrai simulateur de match.",
but:"Lire tard, partir vite, frapper équilibré.",
variantes:["Une balle courte surprise toutes les 6-8 balles","3 zones + variation coupé/tendu"],
critere:"Série de 20 : ≥ 16 en 2 zones, ≥ 13 en 3 zones."},
// BLOC & CONTRE
{id:"b1", name:"Bloc actif placé", cat:"bloc", dur:8,
desc:"Face à un topspin régulier, travaille le bloc comme un COUP : prise de balle tôt, angle fermé, et surtout placement alterné (coude, grand angle, fond). Un bon bloqueur fait courir le topspinneur.",
but:"Transformer la défense en reprise d'initiative.",
variantes:["Bloc amorti une balle sur trois","Bloc poussé (avec avant-bras) sur balle haute"],
critere:"12 blocs consécutifs dont 6 qui déplacent réellement l'attaquant."},
{id:"b2", name:"Contre-top proche de table", cat:"bloc", dur:8,
desc:"Sur le top adverse, contre-toppe par-dessus le rebond, geste court, prise de balle montante. C'est un coup de timing pur : rate-le 20 fois, la 21ᵉ paiera. Réservé aux balles à mi-hauteur, pas aux missiles.",
but:"Ajouter le contre-top comme option de pression immédiate.",
variantes:["Contre-top croisé uniquement, puis ligne","En diagonale revers (contre-top banane)"],
critere:"5/10 contre-tops dans la table — à ce coup-là, 50 % est un excellent taux."},
{id:"b3", name:"Défense mixte : bloc-top-lob", cat:"bloc", dur:8,
desc:"Le partenaire attaque librement, tu alternes selon la balle : bloc proche, top mi-distance, lob si éjecté. Apprendre à changer de distance SANS paniquer est une compétence à part entière.",
but:"Rester dans le point quel que soit le recul imposé.",
variantes:["Interdiction de perdre le point en moins de 4 balles","Revenir à la table dès que possible (règle : 1 lob max)"],
critere:"Gagner 3 points sur 11 en situation full défense (c'est déjà beaucoup)."},
// SCHÉMAS
{id:"h1", name:"Service court + 3ᵉ balle CD", cat:"schemas", dur:10,
desc:"Ton service court coupé, remise poussette du partenaire (consigne), ouverture CD — le schéma roi. Répète-le jusqu'à ce que la séquence entière soit UN seul mouvement mental. Puis le partenaire varie la direction de la poussette.",
but:"Industrialiser ton point de marque n°1.",
variantes:["Remise aléatoire (courte OU longue) : décision 3ᵉ balle","3ᵉ balle puis 5ᵉ balle libre"],
critere:"7/10 schémas conclus par une 3ᵉ balle de qualité match."},
{id:"h2", name:"Service long + top revers direct", cat:"schemas", dur:8,
desc:"Service long rapide au coin revers, remise bloc/contre du partenaire, top revers immédiat dans la foulée. Le schéma « surprise » à sortir 2-3 fois par set, jamais plus.",
but:"Un deuxième schéma de marque prêt à l'emploi.",
variantes:["Service long au coude, 3ᵉ balle CD ou RV selon la remise"],
critere:"6/10 points gagnés ou dominés dès la 3ᵉ balle."},
{id:"h3", name:"Remise banane + 5ᵉ balle", cat:"schemas", dur:10,
desc:"Côté relanceur : service court adverse, banane, bloc adverse (consigne), et TA 5ᵉ balle (pivot ou revers). Le schéma du relanceur moderne : voler l'initiative dès la remise.",
but:"Construire un plan de point même quand tu ne sers pas.",
variantes:["Banane ligne / croisée sur annonce","Bloc adverse aléatoire, 5ᵉ balle libre"],
critere:"6/10 séquences où l'initiative est à toi après la 5ᵉ balle."},
{id:"h4", name:"11 points : schéma serveur imposé", cat:"schemas", dur:10,
desc:"Set en 11 points, mais TOUS tes points au service doivent commencer par le schéma travaillé du jour (annoncé avant). L'adversaire joue libre. La contrainte force l'exécution sous pression de score.",
but:"Transférer le schéma de l'exercice au match.",
variantes:["L'adversaire connaît le schéma (pire cas) — il faut le gagner quand même"],
critere:"Gagner ≥ 4 points sur tes services en respectant le schéma."},
{id:"h5", name:"11 points : relanceur imposé", cat:"schemas", dur:10,
desc:"Miroir du précédent : à la remise, obligation d'attaquer toute balle longue et de jouer court ou banane sur toute balle courte. Zéro poussette de confort autorisée.",
but:"Éradiquer la remise passive sous pression.",
variantes:["Défi : annoncer « courte » ou « banane » avant le service adverse"],
critere:"≤ 2 remises passives sur le set entier."},
// MATCH
{id:"m1", name:"Sets à thème", cat:"match", dur:15,
desc:"Matchs en 11 points avec contrainte : « tout sur le revers adverse », « aucun service long », « gagner uniquement en 3ᵉ balle »… La contrainte crée la lucidité tactique que le match libre n'enseigne jamais.",
but:"Apprendre à gagner d'une manière choisie, pas subie.",
variantes:["Contrainte secrète (chacun devine celle de l'autre)","Contrainte qui change à chaque set"],
critere:"Respect de la contrainte > résultat du set. Les deux, c'est la maîtrise."},
{id:"m2", name:"Montante à handicap", cat:"match", dur:15,
desc:"Sets en 11 points où tu démarres à 0-5 puis 0-7. Travaille l'urgence, la première balle de qualité, et le refus de la panique. Le handicap simule les fins de set serrées mieux que n'importe quoi.",
but:"Jouer chaque point comme un point de money-time.",
variantes:["Handicap inversé : tu mènes 7-0 et dois « tenir » (gérer l'avance)"],
critere:"Gagner 1 set sur 3 en partant de 0-5."},
{id:"m3", name:"Match complet avec plan écrit", cat:"match", dur:20,
desc:"Au meilleur des 5, mais AVANT : écris 3 lignes de plan (mes 2 schémas de marque, la faiblesse adverse ciblée, mon plan B si ça déraille). Entre les sets, 1 minute pour relire et ajuster. Après : 3 lignes de debrief.",
but:"Faire du match un acte tactique documenté, pas un flux d'instinct.",
variantes:["Un coach/partenaire tient le plan et vérifie que tu le suis"],
critere:"Le debrief identifie précisément où le plan a tenu / cassé."},
// PHYSIQUE
{id:"p1", name:"Fentes multidirectionnelles", cat:"physique", dur:8,
desc:"Fentes avant, latérales et arrière-croisées, 3 × 8 par direction, avec ou sans charge légère. La fente latérale est LE mouvement du grand écart coup droit — renforce-la en priorité.",
but:"Force des appuis dans les trois plans du jeu.",
variantes:["Avec haltères légers","Version sautée (dynamique) en fin de série"],
critere:"3 séries complètes, genou aligné, sans douleur."},
{id:"p2", name:"Rotations medicine ball", cat:"physique", dur:8,
desc:"Lancers rotatifs de medicine ball (3-5 kg) contre un mur : position de top CD, rotation explosive hanche-tronc, relâchement du bras. 4 × 6 par côté. C'est la centrale électrique du topspin.",
but:"Puissance de rotation transférable directement au top.",
variantes:["Lancer à genoux (isole le tronc)","Scoop toss vers le haut (chaîne complète)"],
critere:"Puissance constante sur les 4 séries — si ça baisse, stop."},
{id:"p3", name:"Gainage rotatif & anti-rotation", cat:"physique", dur:8,
desc:"Pallof press (élastique, anti-rotation) 3 × 10 par côté + planche avec rotation 3 × 8 + side plank 2 × 30 s. Le tronc du pongiste doit produire ET freiner la rotation des milliers de fois par semaine.",
but:"Un tronc qui protège le dos et transmet la puissance.",
variantes:["Pallof en fente (instabilité)","Planche + touche d'épaule"],
critere:"Séries complètes sans compensation du bassin."},
{id:"p4", name:"Pliométrie basse : skater jumps", cat:"physique", dur:6,
desc:"Sauts latéraux d'un appui sur l'autre (skater jumps), réception amortie et stable, 4 × 10. Puis 3 × 15 s de petits sauts d'appuis rapides sur place. La vitesse latérale se construit ici, pas à la table.",
but:"Réactivité latérale et qualité de réception.",
variantes:["Skater avec pause 1 s en réception (stabilité)","Sur ligne : franchissements latéraux rapides 3 × 20 s"],
critere:"Réceptions silencieuses et stables jusqu'à la dernière série."},
{id:"p5", name:"Prophylaxie épaule & poignet", cat:"physique", dur:7,
desc:"Élastique léger : rotations externes coude au corps 3 × 15, élévations en Y-T-W 2 × 10, puis extensions/flexions de poignet lestées légères 2 × 15. Ennuyeux, invisible, et c'est ce qui te fera jouer encore à 60 ans.",
but:"Blinder la coiffe des rotateurs et le poignet contre le volume de topspin.",
variantes:["À faire aussi les jours OFF (10 min)"],
critere:"Zéro douleur, brûlure musculaire légère en fin de série."},
// RETOUR AU CALME
{id:"q1", name:"Étirements chaîne complète", cat:"retour", dur:6,
desc:"Hanches (pigeon, psoas), ischio-jambiers, avant-bras et poignets, épaules (bras croisé, sleeper stretch léger). 30 à 45 secondes par position, respiration lente.",
but:"Rendre au corps ce que la séance a pris.",
variantes:["Ajouter 2 min de rouleau (quadriceps, dos)"],
critere:"Toutes les zones passées, sans précipitation."},
{id:"q2", name:"Debrief 3 lignes", cat:"retour", dur:4,
desc:"Avant de quitter la salle : note dans le carnet (onglet Carnet) — ce qui a progressé aujourd'hui, ce qui a résisté, LA priorité de la prochaine séance. Une séance non débriefée est à moitié perdue.",
but:"Transformer la sueur en apprentissage cumulatif.",
variantes:[],
critere:"3 lignes écrites, une priorité claire pour la prochaine séance."}
];

// Fiches tactiques : {id, title, icon, points[]}
const TACTICS = [
{id:"t1", title:"Contre un défenseur", icon:"🛡️", points:[
"Patience d'abord : le défenseur gagne quand tu t'énerves. Fixe-toi une règle — jamais deux attaques risquées d'affilée.",
"Varie la rotation de tes tops (fort coupé de retour = top très frotté ; balle flottante = top frappé) et surtout la LONGUEUR : une balle courte au milieu de l'échange le tue.",
"Attaque son coup droit défensif (souvent moins régulier que le revers-picots) et finis au corps, pas dans les angles où il pivote.",
"Sers court et attaque la remise poussée : ne le laisse pas s'installer à 3 mètres.",
"Compte tes fautes directes : contre un défenseur, un match se perd à 60 % sur TES fautes, pas sur ses points."]},
{id:"t2", title:"Contre un pousseur / bloqueur passif", icon:"🧱", points:[
"Il vit de ton impatience et de tes demi-attaques. Décide : soit tu pousses MIEUX que lui (placé, coupé, coins), soit tu ouvres FRANCHEMENT — jamais entre les deux.",
"Ouvre sur sa poussette la plus faible (souvent celle qu'il fait en reculant) et joue ta première attaque en rotation, pas en vitesse : son bloc se nourrit de ta vitesse.",
"Balle au coude systématiquement dès qu'il bloque bien les angles.",
"Sers long-rapide de temps en temps : les pousseurs détestent être pressés à la remise.",
"Accepte des échanges longs : ta condition physique fait partie du plan."]},
{id:"t3", title:"Contre un frappeur rapide", icon:"⚡", points:[
"Coupe le rythme : services courts très coupés, remises courtes, balles sans vitesse qu'il doit produire seul — les frappeurs se nourrissent de TA vitesse.",
"Premier top très frotté et placé au coude plutôt que tendu dans l'angle : donne-lui de la rotation à gérer, pas de la vitesse à renvoyer.",
"Recule d'un demi-pas sur ses initiatives, bloc actif sur la première, contre sur la deuxième.",
"S'il prend la balle tôt, vise ses hanches : le joueur rapide proche de la table n'a pas de place au corps.",
"Reste à 0-0 dans ta tête : les frappeurs font des séries — encaisse la série, le taux de faute revient toujours."]},
{id:"t4", title:"Contre un gaucher", icon:"🫲", points:[
"Inverse ta carte mentale : SON revers est sur TA diagonale coup droit. Le service court latéral qui sort côté droit l'ouvre au lieu de le fermer.",
"Sers court sur son coup droit (au milieu-droit de ta table) : c'est la zone que les droitiers ne travaillent jamais contre gauchers.",
"La diagonale revers-revers classique n'existe plus : ton revers croisé arrive sur son coup droit. Joue ton revers LIGNE plus souvent que d'habitude.",
"Son pivot le déporte vers TON coup droit : après son pivot, la ligne droite sur son coude est presque toujours ouverte.",
"Prends 5 minutes d'échauffement mental spécifique avant le match : visualise les angles inversés."]},
{id:"t5", title:"Contre picots / anti-top", icon:"🧷", points:[
"Identifie VITE quelle face porte le picot et suis-la (beaucoup « twiddlent » — retournent la raquette).",
"Règle d'or picots longs : la rotation revient inversée. Ta poussette revient flottante, ton top revient coupé. Donc : pousse sur ce qui revient coupé, attaque ce qui revient flottant — et surtout joue des balles SANS rotation sur le picot (balle morte = retour mort, facile à attaquer).",
"Ne change pas de plan tous les deux points : contre picots, la constance du plan bat l'inspiration.",
"Attaque en priorité la face lisse / son coup droit, et sers long-rapide sur le picot pour des retours hauts.",
"Si tu perds le fil : reviens à « balle lente longue au picot, attaque du retour flottant ». Ce schéma simple gagne des matchs entiers."]},
{id:"t6", title:"Le money-time : 9-9 et balles de match", icon:"🎯", points:[
"À 9-9, joue ton schéma n°1 — celui répété mille fois — PAS une inspiration nouvelle. La pression se gère par l'automatisme, pas par le génie.",
"Prends ton temps légal : essuie la main, respire 4 secondes, décide TOUT le point (service, 3ᵉ balle, plan B) AVANT de servir.",
"Sur balle de match CONTRE toi : une seule pensée — « remise profonde au coude, et je joue ». Pas de héroïsme à la remise.",
"Sur balle de match POUR toi : même service que ton meilleur point du set. L'adversaire s'attend à la surprise ; sers la certitude.",
"Le score n'existe pas pendant l'échange. Il n'existe qu'entre les points — et entre les points, c'est TOI qui décides du récit (« je suis en train de revenir » vs « je suis en train de craquer »)."]},
{id:"t7", title:"Routine entre les points", icon:"🔄", points:[
"3 à 5 secondes fixes : regarde ta raquette ou le sol (coupe le regard adverse), une respiration longue, un mot-clé technique (« jambes », « tôt », « relâché »).",
"Après un point perdu : UNE analyse factuelle max (« remise trop haute »), puis passage au plan du point suivant. Interdiction de rejouer le point mentalement plus d'une fois.",
"Après un point gagné : ancre-le (poing discret, « oui » intérieur) — le cerveau retient ce qu'on célèbre.",
"Tous les 3-4 points : un check corporel express — épaules basses ? mâchoire desserrée ? appuis vivants ?",
"La routine est ce qui reste quand le jeu te lâche. Travaille-la à l'entraînement, sinon elle n'existera pas en match."]},
{id:"t8", title:"Préparer un plan de match", icon:"📋", points:[
"3 lignes suffisent : (1) mes deux schémas de marque, (2) la faiblesse adverse que je cible en priorité, (3) mon plan B si le plan A ne marque plus.",
"Observe l'échauffement adverse : remise préférée sur balle courte ? pivot fréquent ? distance à la table ? Tu as 2 minutes d'espionnage légal — utilise-les.",
"Décide de tes services des 4 premiers points À L'AVANCE : ils t'informent (comment remet-il court ? long ?) autant qu'ils marquent.",
"Entre les sets : une question unique — « qu'est-ce qui marche, qu'est-ce que j'arrête ? ». Pas de refonte totale à 1-1.",
"Après le match, gagné ou perdu : 3 lignes de debrief dans l'onglet Matchs. Dix matchs debriefés valent une saison de matchs oubliés."]},
{id:"t9", title:"Après une défaite", icon:"🌧️", points:[
"Délai de décence : 30 minutes sans analyse. À chaud, tu ne verras que les balles de match ratées, jamais les vraies causes.",
"Puis trois questions froides : où le match s'est-il VRAIMENT joué (souvent au 2ᵉ set, pas au 5ᵉ) ? Quel schéma adverse n'ai-je jamais résolu ? Qu'est-ce que je répète depuis 3 défaites ?",
"Une défaite = UN chantier d'entraînement, pas cinq. Choisis le plus rentable et programme-le dans tes deux prochaines séances.",
"Sépare le résultat de la performance : on peut bien jouer et perdre 3-2 contre plus fort — et jouer faux en gagnant 3-0. Note les deux séparément dans le carnet.",
"La défaite qui ne change pas ton entraînement suivant n'a servi à rien. Celle qui le change vaut une victoire."]}
];

// Checklist d'avant-match
const PREMATCH = [
"Corde ou course légère 5 min — transpirer AVANT le premier échange",
"Mobilité épaules, hanches, poignets (3 min)",
"Gammes CD et RV, cadence progressive (5 min)",
"10 ouvertures sur poussette de chaque côté",
"15 services : mes 2 schémas + 3 surprises",
"5 remises courtes + 5 bananes sur service court",
"Plan de match écrit : 2 schémas de marque, faiblesse ciblée, plan B",
"Hydratation + banane/barre 45 min avant",
"Maillot de rechange, serviette, 2ᵉ raquette dans le sac",
"Mot-clé du jour choisi (« jambes », « tôt », « relâché »…)"
];
